name: Deploy Supabase

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
    secrets:
      token:
        required: true
      db-password:
        required: true

jobs:
  deploy-staging:
    name: Deploy Supabase
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.token }}
      SUPABASE_DB_PASSWORD: ${{ secrets.db-password }}
      SUPABASE_PROJECT_ID: ${{ inputs.project-id }}

    steps:
      - name: Log Info
        run: |
          echo "env: ${{ github.ref_name }}"
          echo "project: $SUPABASE_PROJECT_ID"
          echo "token: $SUPABASE_ACCESS_TOKEN"
          echo "db-pwd: $SUPABASE_DB_PASSWORD"
      