name: Deploy to Production

on:
  push:
    branches: main

env:  
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID}}

jobs:
  deploy-staging:
    name: Setup & Deploy Supabase to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy Functions
        run: supabase functions deploy --project-ref $PROJECT_ID