# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SpiritWave CI

on: [push, pull_request]

env:  
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID}}

jobs:
  run-ci:
    name: Lint project and deploy functions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Use Deno v1 latest
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Install CI Dependencies
        run: |
          cd ./www
          npm ci
          cd ..
      
      - name: Linting
        run: npm run lint

      - name: Setup Supabase
        if: github.base_ref == 'main'
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy Functions
        if: github.base_ref == 'main'
        run: supabase functions deploy --project-ref $PROJECT_ID